ghn.enabled=true
ghn.env=staging
ghn.baseUrl=https://dev-online-gateway.ghn.vn/shiip/public-api

ghn.token=7c9bd179-6978-11f1-a973-aee5264794df
ghn.shopId=200738

ghn.fromName=MyCosmeticShop
ghn.fromPhone=0856272116
ghn.fromAddress=Số nhà 316, đường số 2, khu phố 3, Phường Linh Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh
ghn.fromDistrictId=3695
ghn.fromWardCode=90737

ghn.demoToDistrictId=0
ghn.demoToWardCode=

ghn.defaultWeight=500
ghn.defaultLength=20
ghn.defaultWidth=15
ghn.defaultHeight=10
ghn.insuranceValue=100000
ghn.codEnabled=false
ghn.requiredNote=KHONGCHOXEMHANG