# ===============================
# MyCosmeticShop SMTP Config
# ===============================

mycosmetic.mail.username=mycosmetic0101@gmail.com
mycosmetic.mail.password=puqvewsvvsrjfkgi
mycosmetic.mail.from=mycosmetic0101@gmail.com
mycosmetic.mail.fromName=MyCosmeticShop

mycosmetic.app.baseUrl=http://localhost:8080/Gradle___com_webshop_app___MyCosmeticShop_war__exploded_

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true
mail.smtp.connectiontimeout=12000
mail.smtp.timeout=12000
mail.smtp.writetimeout=12000
mail.debug=true