

# Mã website/Terminal ID VNPay cấp
vnp.tmnCode=O4DETZ8T
# Secret Key dùng để ký checksum giao dịch
vnp.hashSecret=9HPP1QD7GRC48XX4M0HEHQ9K40UX8C3P

# URL thanh toán môi trường TEST/Sandbox
vnp.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# URL VNPay chuyển người dùng về sau khi thanh toán xong
# Route trong project: @WebServlet("/payment/vnpay-return")
vnp.returnUrl=https://headroom-denial-revolving.ngrok-free.dev/Gradle___com_webshop_app___MyCosmeticShop_war_exploded/payment/vnpay-return

# URL IPN để VNPay gọi server-to-server cập nhật kết quả thanh toán
# Route trong project: @WebServlet("/payment/vnpay-ipn")
vnp.ipnUrl=https://headroom-denial-revolving.ngrok-free.dev/Gradle___com_webshop_app___MyCosmeticShop_war_exploded/payment/vnpay-ipn

# Thông tin giao dịch mặc định
vnp.orderType=other
vnp.locale=vn
vnp.currCode=VND

# Thời gian hết hạn thanh toán, đơn vị phút
vnp.expireMinutes=15

# Project hiện đang để false để tránh lỗi định dạng/ngân hàng test không nhận expire date
vnp.sendExpireDate=false

# Bật log debug khi test. Khi nộp/chạy ổn có thể đổi thành false.
vnp.debug=true
