vnp.tmnCode=72GLCXDR
vnp.hashSecret=8VLD43S1RVNCZ8KHUXU443HRCP3YMMT
vnp.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

vnp.returnUrl=https://twistable-winnings-refresh.ngrok-free.dev/Gradle___com_webshop_app___MyCosmeticShop_war__exploded_/payment/vnpay-return

vnp.orderType=other
vnp.expireMinutes=15
vnp.sendExpireDate=false
vnp.debug=true